Improve UI
Planning-Poker-Teams/planning-poker pull request #47
Opened 2023-10-26 14:20 UTC by AsmardPing

- Added invite button (that copies URL)
- Added graphical representation of approval rate in result table
- Only shows result table when different options were selected, otherwise consensus cat appears in larger version
- Added Task Control Row and centralised all control functions for the task there
- Moved participants to the bottom of the screen
- Added new Modal for "New Task"
- Re-arranged voting screen to better fit screen dimensions
- Added (limited) mobile screen support
- switched prettier airbnb config from external dependency to direct configuration in prettierrc
- added (limited) connection problem handling

2023-10-31 14:04 UTC, felixabele requested changes
Nice work! 

I left some comments, no bugs in the code AFAIC.
I've noticed we have some really complex components and could refactor some by extracting a few dump components to decrease repetitive  markup e.g. buttons or dialog templates. But nothing that blocks this PR.

There is just one weird behaviour I've noticed. You can reproduce with the following steps:
- you have 2 users
- user 1 votes any number
- user 2 votes a different number
- display results
- user 2 leaves
- => both rows stay (which makes sense) but the values both change to 100% now

Vielleicht noch bei EstimationResult einen Test für die Prozent-Anzeige hinzufügen.

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/components/EstimationResult.vue
> +          : `All ${sortedEntries[0]?.names.length} participants were to confused to select anything. 🧐`
```suggestion
          : `All ${sortedEntries[0]?.names.length} participants were too confused to select anything. 🧐`
```

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/components/EstimationResult.vue
> +  agreement: (e1: Entry, e2: Entry): number => (e1.names.length < e2.names.length ? -1 : 1),
Maybe reduce duplication and increase readability, but its just a suggestion:
```
const sortByVotes = (e1: Entry, e2: Entry): number => (e1.names.length < e2.names.length ? -1 : 1);

const sortFunctions = {
  size: (e1: Entry, e2: Entry): number =>
    cardDeck.value.indexOf(e1.value) - cardDeck.value.indexOf(e2.value),
  votes: sortByVotes,
  agreement: sortByVotes
};
```

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/components/OngoingEstimation.vue
> +            // @ts-ignore TODO: create proper typing for cardRefList
should we solve this TODO in this PR?

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/components/RoomHeader.vue
> +  navigator.clipboard.writeText(`https://planningpoker.cc${window.location.pathname}`);
Maybe `window.location.pathname` would be better, so we wouldn't have to hardcode the domain. Or do I miss something?

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/components/TaskHeader.vue
> +        <button
We should really think about extracting some dump components such as these buttons to DRY code. These long repetitive class concatenations are hard to read.

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/store/mutations.ts
> +    state.connectionState = 'CONNECTED';
maybe use the enum from `ConnectionState.CONNECTED`

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/store/mutations.ts
> +    state.connectionState = 'NOT_CONNECTED';
maybe use the enum from `ConnectionState.NOT_CONNECTED`

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/store/websocketPlugin.ts
> +      console.log(event);
```suggestion
      console.error('[error] Connection error, see log for details.');
      console.error(event);
```

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/store/websocketPlugin.ts
> +        console.log(`[close] Connection closed cleanly, code=${event.code}.`);
```suggestion
        console.info(`[close] Connection closed cleanly, code=${event.code}.`);
```

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/store/websocketPlugin.ts
> +        console.log(`[close] Connection died, code=${event?.code}.`);
```suggestion
        console.error(`[close] Connection died, code=${event?.code}.`);
```

2023-10-31 14:04 UTC, felixabele commented on packages/frontend/src/views/Room.vue
>      return '';
Maybe less spaghetti but see your self what you like better:
```
const taskName = computed(() => {
  const { ongoingEstimation, estimationResult } = store.state;
  return ongoingEstimation?.taskName || estimationResult?.taskName || ''
});
```

2023-11-02 13:52 UTC, AsmardPing commented on packages/frontend/src/store/mutations.ts
> +    state.connectionState = 'CONNECTED';
This causes the error "index.ts:38 Uncaught ReferenceError: Cannot access 'mutations' before initialization
    at index.ts:38:3"
    Unfortunately I haven't found a way around it.

2023-11-02 13:55 UTC, AsmardPing commented on packages/frontend/src/components/OngoingEstimation.vue
> +            // @ts-ignore TODO: create proper typing for cardRefList
I was unsure how to do it. The typescript error was already there beforehand and I didn't implement this part. The error is: 
Type 'Element | ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}, {}, string>, {}> | null' is not assignable to type 'VueElement'.
  Type 'null' is not assignable to type 'VueElement'.

2023-11-02 14:03 UTC, AsmardPing commented on packages/frontend/src/components/EstimationResult.vue
> +  agreement: (e1: Entry, e2: Entry): number => (e1.names.length < e2.names.length ? -1 : 1),
I would personally leave it as it is, as I can see the sort logic of all sort options at one glance right now (even if there is one reptition in it). When starting to outsource it to other methods that would become more effort.

2023-11-02 14:57 UTC, AsmardPing commented
@felixabele Bin alles durchgegangen. Das beschriebene Problem mit der sich verändernden Prozentanzeige wenn eine Person den Raum verlässt habe ich behoben. Außerdem alles was "resolved" ist. Ansonsten siehe meine Kommentare :)

2023-11-03 14:50 UTC, felixabele commented on packages/frontend/src/components/OngoingEstimation.vue
> +            // @ts-ignore TODO: create proper typing for cardRefList
Try with Typecasting from Element to VueElement:
```
          el => {
            cardRefList[index] = el as VueElement;
          }
```

2023-11-06 09:44 UTC, AsmardPing commented on packages/frontend/src/components/OngoingEstimation.vue
> +            // @ts-ignore TODO: create proper typing for cardRefList
it worked :D Could have realised that myself based on the error message actually. Thanks!

2023-11-06 14:29 UTC, felixabele approved these changes

2023-11-14 09:03 UTC, felixabele commented
Closed in Favour of: https://github.com/Planning-Poker-Teams/planning-poker/pull/48

2023-11-14 09:03 UTC, closed without merging