Minor layout issues
Planning-Poker-Teams/planning-poker pull request #51
Opened 2024-03-21 07:06 UTC by felixabele

2024-03-21 15:44 UTC, AsmardPing requested changes
Danke dir!
Hab noch ein paar Fragen angefügt. Generell zwar kleine Änderungen aber mit einigem Impact, echt cool dass du das eingeschoben hast. Find gerade auch die Icons sehr gut.

2024-03-21 15:44 UTC, AsmardPing commented on infrastructure/main-backend.tf
Was passiert hier?

2024-03-21 15:44 UTC, AsmardPing commented on packages/frontend/src/components/NewTaskDialog.vue
Bzgl. Character Limit: Würde vorschlagen, dass wir es nicht komplett entfernen. Sonst besteht wirklich das Potential, die UI ziemlich zu zerlegen. 
<img width="1455" alt="grafik" src="https://github.com/Planning-Poker-Teams/planning-poker/assets/20561186/5856e130-66be-44e8-83ef-8a91de88cf30">
Würde vorschlagen die maximale Länge auf 100 oder so zu legen, oder line clamp zu verwenden: https://tailwindcss.com/docs/line-clamp

2024-03-21 15:44 UTC, AsmardPing commented on packages/frontend/src/components/ParticipantsList.vue
Wenn ich das richtig sehe ist hier irgendwie die Formatierung verschoben worden?

2024-03-22 05:33 UTC, felixabele commented on infrastructure/main-backend.tf
Ich bin jetzt zum zweiten mal über ein Issue gestolpert, dass das Deployment failed wenn der Branch-Name so was wie: `feat/bla-blub` lautet (der Slash macht da Probleme). Ich hatte das versucht zu behandeln durch das replacement, macht dann aber an anderer Stelle Probleme. Habe das mal in die Readme mit aufgenommen, damit andere nicht auch darüber stolpern. Irgendwann sollten wir das behandeln. Das Replacement habe ich rausgenommen, danke für das Heads-Up

2024-03-22 13:05 UTC, AsmardPing approved these changes

2024-03-22 13:10 UTC, merged